# The data structure

```{r, echo=FALSE}
knitr::kable(head(data()),caption="Table: The header")
```

# The Kaplan-Meier curve

The overal survival probability can be seen from the Kaplan-Meier curve.

```{r km, fig.height=6.5, fig.width=6.5, echo=FALSE}
kmfit <- survfit(as.formula(km_formulaText()), data = data())
autoplot(kmfit)+
ggplot2::theme_bw()+
cowplot::theme_cowplot(12)+
ggplot2::xlab("Time")+
ggplot2::ylab("Overall survival probability")+
ggplot2::ggtitle(km_formulaText())
kmfit_strata <- survfit(as.formula(km_formulaText_strata()), data = data())
autoplot(kmfit_strata)+
ggplot2::theme_bw()+
cowplot::theme_cowplot(12)+
ggplot2::xlab("Time")+
ggplot2::ylab("Overall survival probability")+
ggplot2::ggtitle(km_formulaText_strata())
```

# The Cox model

```{r cox, fig.height=6.5, fig.width=6.5, message=FALSE, echo=FALSE}
coxfit <- coxph(as.formula(cox_formulaText()), data = data())
if (input$summary) summary(coxfit)

if (grepl(strata(), covariates()))
{
  new_df <- with(data(), {
                 grp <- unique(sort(data()[[strata()]]))
                 df <- data.frame(distinct(data()[strata()]),
                                  as.data.frame(lapply(apply(data()[setdiff(names(data()),strata())],2,mean,na.rm=TRUE),rep,length(grp)))
                       )
                 rownames(df) <- df[[strata()]]
                 df
                 }
                )
  new_df

  fit <- survfit(coxfit, newdata = new_df)
  if (input$summary) print(summary(fit))
  ggsurvplot(fit, conf.int = TRUE, palette = "Dark2", censor = FALSE,
             surv.median.line = "hv", data=data()) + ggtitle(cox_formulaText())
}
```
